## Dataset

In [1]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
sequence_length = 5

sample1 = 'We are learning AI'
sample2 = 'AI is a CS topic'
sentences = [sample1, sample2]
labels = [0, 1]
print(sentences)

['We are learning AI', 'AI is a CS topic']


/Users/quangvinh/miniconda3/envs/torchenv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [2]:
from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self, sentences, labels, tokenizer, max_len):
        super().__init__()
        self.sentences = sentences
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.sentences)
    
    def __getitem__(self, idx):
        sentence = self.sentences[idx]
        sentence_label = self.labels[idx]

        tokens = sentence.split()
        tokens = self.tokenizer.convert_tokens_to_ids(tokens)
        tokens = self.pad_and_truncate(tokens)

        return tokens, sentence_label
    
    def pad_and_truncate(self, tokens): 
        pad_id = self.tokenizer.pad_token_id
        if len(tokens) < self.max_len:
            padded_tokens = tokens + [pad_id] * (self.max_len - len(tokens))            
        else:
            padded_tokens = tokens[:self.max_len]
            
        return torch.tensor(padded_tokens)

In [3]:
from torch.utils.data import DataLoader

train_set = MyDataset(sentences, labels, tokenizer, sequence_length)

batch_size = 1
train_loader = DataLoader(train_set, batch_size)

In [4]:
for x,y in train_loader:
    print(x)
    print(y)

tensor([[ 100, 2024, 4083,  100,    0]])
tensor([0])
tensor([[ 100, 2003, 1037,  100, 8476]])
tensor([1])


## Embedding

In [5]:
import torch.nn as nn

embedding = nn.Embedding(8, 4)
print(embedding)

Embedding(8, 4)


In [6]:
print(embedding.weight)

Parameter containing:
tensor([[ 0.5988, -0.1354, -0.0097, -1.8604],
        [-1.4412,  0.8351, -0.2374, -1.1283],
        [ 0.0346, -2.3051,  0.9996,  0.1789],
        [ 0.0858, -1.0797, -1.2667, -0.3157],
        [-0.2618, -1.1648, -0.3752, -0.5289],
        [ 0.2459, -0.5419,  0.7793, -0.3084],
        [-0.8312, -0.7859,  1.2632, -0.9244],
        [ 0.1343,  0.4508, -2.3906, -1.1909]], requires_grad=True)


In [7]:
input1 = torch.tensor([0, 3, 6, 1, 0], dtype=torch.long)
output1 = embedding(input1)
print(output1)

tensor([[ 0.5988, -0.1354, -0.0097, -1.8604],
        [ 0.0858, -1.0797, -1.2667, -0.3157],
        [-0.8312, -0.7859,  1.2632, -0.9244],
        [-1.4412,  0.8351, -0.2374, -1.1283],
        [ 0.5988, -0.1354, -0.0097, -1.8604]], grad_fn=<EmbeddingBackward0>)
